using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace LPSE_UGM_Winner_Parser
{
    public partial class crawler : Form
    {
        public crawler()
        {
            InitializeComponent();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            startBox.Text = "1";
            endBox.Text = "8000";
            timeoutBox.Text = "60";
            retryBox.Text = "3";
        }

        //start script python
        private void startScript_Click(object sender, EventArgs e)
        {
            string tmp = Path.GetDirectoryName(System.AppDomain.CurrentDomain.BaseDirectory) + @"\Resources\";

            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "py";
            start.Arguments = string.Format(tmp + "winner_get.py {0} {1} {2} {3} {4}", locCombo.SelectedItem.ToString(), startBox.Text, endBox.Text, timeoutBox.Text, retryBox.Text);
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true;//no python window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    //string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    MessageBox.Show(result);
                    Console.Write(result);
                }
            }
        }
    }
}
